-- MySQL Script generated by MySQL Workbench
-- Tue Apr 23 04:32:27 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema catalogs
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema catalogs
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `catalogs` DEFAULT CHARACTER SET utf8 ;
USE `catalogs` ;

-- -----------------------------------------------------
-- Table `catalogs`.`brands`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catalogs`.`brands` ;

CREATE TABLE IF NOT EXISTS `catalogs`.`brands` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `nombre_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `catalogs`.`models`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `catalogs`.`models` ;

CREATE TABLE IF NOT EXISTS `catalogs`.`models` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `brands_id` INT NOT NULL,
  `average_price` FLOAT NOT NULL,
  PRIMARY KEY (`id`, `brands_id`),
  INDEX `fk_models_brands_idx` (`brands_id` ASC) VISIBLE,
  CONSTRAINT `fk_models_brands`
    FOREIGN KEY (`brands_id`)
    REFERENCES `catalogs`.`brands` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

SELECT b.id, b.name, m.name, m.average_price  FROM BRANDS b
INNER JOIN MODELS m;

SELECT b.id, b.name, m.name, m.average_price  FROM BRANDS b
INNER JOIN MODELS m
ON brands_id = 1;

SELECT * FROM MODELS;
SELECT * FROM MODELS WHERE ID = 1;
INSERT INTO BRANDS (name) VALUES ("Acura"); 
SELECT * FROM BRANDS;
INSERT INTO MODELS (name, brands_id, average_price) VALUES ("ILX", 1, 40000 );
SELECT * FROM MODELS;
UPDATE  MODELS SET average_price = 20000 WHERE id = 1;
SELECT * FROM MODELS;

SELECT b.id, b.name, m.name, m.average_price  FROM BRANDS b
INNER JOIN MODELS m
ON average_price between 20000 and 40000;



show databases;

